### ISSUE TITLE
Javascript problems

### ISSUE THREAD

**Issue by rarose67** [exercism/exercism#4453]
Good evening, I submitted the my solution to the "Leap" problem in the Javascript track, but I can't get the next one to unlock.  What should I do?  Also, I tried the simple-cipher problem in independent mode, but get this message when I run npm test:

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Bob\Exercism\javascript\simple-cipher\node_modules\graceful-fs\graceful-fs.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! Test failed.  See above for more details.

**Comment by tejasbubane** [comment]
> I submitted the my solution to the "Leap" problem in the Javascript track, but I can't get the next one to unlock. What should I do?

Each core exercise will be reviewed by mentors. Your solution must be in the pending queue. You can either wait for the queue or post the exercise link here and I can have a look.

> at Object. (C:\Users\Bob\Exercism\javascript\simple-cipher\node_modules\graceful-fs\graceful-fs.js:4:13)

Did you run `npm install` before `npm test`? Looks like the packages are missing.
