### ISSUE TITLE
Trouble getting started with ReasonML

### ISSUE THREAD

**Issue by bionikspoon** [exercism/exercism#4768]
Hello!

I'm having an issue getting started with the `reasonml/hello-world` track.

I tried twice.  When I run `npm start` I get the following output:

```sh
npm start

> exercism-reasonml@0.1.0 start /Users/manu/Code/Exercism/reasonml/hello-world
> bsb -make-world -w

ninja: no work to do.
>>>> Start compiling
[1/1] Building __tests__/HelloWorld_test-HelloWorld.cmj

  We've found a bug for you!
  /Users/manu/Code/Exercism/reasonml/hello-world/__tests__/HelloWorld_test.re

  HelloWorld-HelloWorld.cmj not found, cmj format is generated by BuckleScript

>>>> Finish compiling(exit: 1)
^Cnpm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! exercism-reasonml@0.1.0 start: `bsb -make-world -w`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the exercism-reasonml@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/manu/.npm/_logs/2019-03-24T19_04_44_146Z-debug.log
```

Here's a copy of the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/manu/.nvm/versions/node/v11.12.0/bin/node',
1 verbose cli   '/Users/manu/.nvm/versions/node/v11.12.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.7.0
3 info using node@v11.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle exercism-reasonml@0.1.0~prestart: exercism-reasonml@0.1.0
6 info lifecycle exercism-reasonml@0.1.0~start: exercism-reasonml@0.1.0
7 verbose lifecycle exercism-reasonml@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle exercism-reasonml@0.1.0~start: PATH: /Users/manu/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/manu/Code/Exercism/reasonml/hello-world/node_modules/.bin:/Users/manu/.nvm/versions/node/v11.12.0/bin:/usr/local/opt/openssl@1.1/bin:/Users/manu/.rbenv/shims:/Users/manu/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/opt/postgresql@9.6/bin:/usr/local/opt/openssl@1.1/bin:/Users/manu/.local/bin:/Users/manu/.yadr/bin:/Users/manu/.yadr/bin/yadr
9 verbose lifecycle exercism-reasonml@0.1.0~start: CWD: /Users/manu/Code/Exercism/reasonml/hello-world
10 silly lifecycle exercism-reasonml@0.1.0~start: Args: [ '-c', 'bsb -make-world -w' ]
11 silly lifecycle exercism-reasonml@0.1.0~start: Returned: code: 2  signal: null
12 info lifecycle exercism-reasonml@0.1.0~start: Failed to exec start script
13 verbose stack Error: exercism-reasonml@0.1.0 start: `bsb -make-world -w`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/manu/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/manu/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:988:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid exercism-reasonml@0.1.0
15 verbose cwd /Users/manu/Code/Exercism/reasonml/hello-world
16 verbose Darwin 18.2.0
17 verbose argv "/Users/manu/.nvm/versions/node/v11.12.0/bin/node" "/Users/manu/.nvm/versions/node/v11.12.0/bin/npm" "start"
18 verbose node v11.12.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 2
22 error exercism-reasonml@0.1.0 start: `bsb -make-world -w`
22 error Exit status 2
23 error Failed at the exercism-reasonml@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

Any tips on how to proceed?

**Comment by bionikspoon** [comment]
Oh boy, 🤦‍♂️ 

Figured it out!  Had to add the `HelloWorld.re` the file. 

```sh
touch reasonml/hello-world/src/HelloWorld.re
```

I'll leave this up to double as feedback. This is my first time running reasonml locally.  I had no idea what to expect.  That error message is a bit rough!

Alright, thanks y'all!

**Comment by tejasbubane** [comment]
Sorry I just came across this issue. We have [added a stub file](https://github.com/exercism/reasonml/pull/76) for this exercise recently. So this should not be an issue with `hello-world` exercise. But I can see that this might be very confusing for other exercises. I have created an issue to add stub files for all other exercises: https://github.com/exercism/reasonml/issues/78
