### ISSUE TITLE
 FAIL  ./hello-world.spec.js   ● Test suite failed to run

### ISSUE THREAD

**Issue by edb-c** [exercism/exercism#5078]
Hello,
I was able to submit and see that I have same code as others, but am not able to pass the tests.

Please advise.  Thank you.

> exercism-javascript@0.0.0 test /Users/ecofresi/Documents/EXERCISM/javascript/hello-world
> jest --no-cache ./*

 FAIL  ./hello-world.spec.js
  ● Test suite failed to run

    TypeError: /Users/ecofresi/Documents/EXERCISM/javascript/hello-world/hello-world.js: Cannot read property 'bindings' of null

      at Scope.moveBindingTo (node_modules/@babel/traverse/lib/scope/index.js:822:13)
      at convertBlockScopedToVar (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:139:13)
      at PluginPass.VariableDeclaration (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:26:9)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:179:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.215s
Ran all test suites matching /.\/README.md|.\/hello-world.js|.\/hello-world.spec.js|.\/node_modules|.\/package-lock.json|.\/package.json/i.
npm ERR! Test failed.  See above for more details.
[16:40:21] (master) hello-world
// ♥

**Comment by edb-c** [comment]
When I use yarn test - it works..

// ♥ yarn test
yarn run v1.13.0
$ jest --no-cache ./*
 PASS  ./hello-world.spec.js
  Hello World
    ✓ Say Hi! (4ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.74s
Ran all test suites matching /.\/README.md|.\/babel.config.js|.\/hello-world.js|.\/hello-world.spec.js|.\/node_modules|.\/package-lock.json|.\/package.json|.\/yarn.lock/i.
✨  Done in 2.96s.
[16:57:15] (master) hello-world
// ♥

**Comment by edb-c** [comment]
It's working now.  Not sure what happened.

**Comment by sshine** [comment]
Excellent, good to know.

I'm closing this issue, but feel free to update it if something else related fails.
