### ISSUE TITLE
Npm test failed unexpected identifier

### ISSUE THREAD

**Issue by bcameron1489** [exercism/exercism#5221]
Hi, any new tests that I download, npm install and run the test suite I receive the an error.  Challenges that I've previously have downloaded seem to work fine.  The terminal reads as follows:

node_modules/import-local/node_modules/pkg-dir/index.js:5
const pkgDir = async cwd => {
                     ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>

**Comment by bcameron1489** [comment]
If it matters at all I'm running node version 6.4.1 on ubuntu 16.04

**Comment by bcameron1489** [comment]
Updating node to 6.14.2 appears to have resolved the issue

**Comment by SleeplessByte** [comment]
FWIW, per the JavaScript track installation documentation we only support Node LTS and stable versions up. This means: https://nodejs.org/en/. On Node, only even numbers are considered stable.

![image](https://user-images.githubusercontent.com/1964376/77705381-d28b4280-6fbf-11ea-8442-798a3f5acc61.png)
