### ISSUE TITLE
Nucleotide Count Javascript - Test suite failed to run

### ISSUE THREAD

**Issue by ziyafenn** [exercism/exercism#5399]
After installing all node modules, running tests on [this](https://exercism.io/my/solutions/a9df8d0e27f44b3cb148d8f08ef26846) track fails.

```
 ENOENT: no such file or directory, mkdir '/private/var/folders/yk/638g16997p7g9k6psy7vl0nh0000gn/T/jest_dx/jest-transform-cache-8187dc7827c56acfae99e5da0d5b3e85-8ddc4c70947c4ab977b893339f93963e/f9'

      at createDirectory (node_modules/jest-util/build/createDirectory.js:68:10)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:305:37)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:428:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:568:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:606:25)
```

Log attached.

[2020-10-20T10_19_15_422Z-debug.log](https://github.com/exercism/exercism/files/5408024/2020-10-20T10_19_15_422Z-debug.log)

**Comment by ziyafenn** [comment]
Fixed by using node v12
