### ISSUE TITLE
Java test runner on squeaky-clean always returns error

### ISSUE THREAD

**Issue by jmrunkle** [exercism/exercism#5805]
Handle: jmrunkle
Track: java
Exercise: squeaky-clean

Always returns:

> An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.
>
> Please check your code, and if nothing seems to be wrong, try running the tests again.

Even when the implementation of the exercise is perfectly valid Java, like:

```
class SqueakyClean {
    public static String clean(String identifier) {
        return identifier;
    }
}
```

I know that does not solve the exercise, I just wanted something that would certainly compile and should fail some tests (but not everything).

**Comment by jmrunkle** [comment]
My initial suspicion is that the Java test runner may not support unicode characters (it is probably the only exercise with unicode characters). I know the test runner has been working for other exercises at least.

**Comment by jmrunkle** [comment]
NOTE: if I introduce a syntax error, I do get that returned.

For example:

```
class SqueakyClean {
    public static String clean(String identifier) {
        return;
    }
}
```

Returns:

```
Execution failed for task ':squeaky-clean:compileJava'. /opt/test-runner/lib/squeaky-clean/src/main/java/SqueakyClean.java:3: error: incompatible types: missing return value
        return;
        ^
```

Unfortunately, would have to get / see the logs for the Java test runner to know what is breaking it.

**Comment by jmrunkle** [comment]
OK - full disclosure, I have gotten random successes. Trying to see if my actual solution will eventually pass if I keep retrying.

**Comment by SleeplessByte** [comment]
Perhaps this should be in `exercism/java-test-runner`?

**Comment by jmrunkle** [comment]
Perhaps, but I think we need to see the logs to determine if this is specifically a problem with the test runner or some other part of the test runner infrastructure. I suspect the maintainers of the java-test-runner do not have direct access to the relevant logs. iHiD asked for an issue to be filed so I created this here - I assume he can move it and add logs if it belongs specifically in the java-test-runner repo.

**Comment by iHiD** [comment]
Could it be that it's on the 10s timeout boundary, so sometimes its just ok, and sometimes it's just not?

**Comment by jmrunkle** [comment]
> Could it be that it's on the 10s timeout boundary, so sometimes its just ok, and sometimes it's just not?

That's certainly possible, but I thought we might be able to verify that by looking at some logs / information somewhere?

**Comment by jmrunkle** [comment]
Also, it would not strictly be a problem with the solution but with the overhead from the runner since we are seeing this very often.

**Comment by iHiD** [comment]
The issue here is that the JSON being returned contains invalid unicode characters:
```
{"status":"fail","message":null,"tests":[{"name":"omit_lower_case_greek_letters","status":"pass","message":"","output":""},{"name":"spaces","status":"pass","message":"","output":""},{"name":"string","status":"pass","message":"","output":""},{"name":"string_with_no_letters","status":"fail","message":"Expecting empty but was:<\"\uD83D\uDE00\uDE00\uD83D\uDE00\uDE00\uD83D\uDE00\uDE00\">java.lang.AssertionError: \nExpecting empty but was:<\"\uD83D\uDE00\uDE00\uD83D\uDE00\uDE00\uD83D\uDE00\uDE00\">[\n at SqueakyCleanTest.string_with_no_letters(SqueakyCleanTest.java:46), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), \n at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), \n at java.base/java.lang.reflect.Method.invoke(Method.java:566), \n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59), \n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12), \n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56), \n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17), \n at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306), \n at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100), \n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366), \n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103), \n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63), \n at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331), \n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79), \n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329), \n at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66), \n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293), \n at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306), \n at org.junit.runners.ParentRunner.run(ParentRunner.java:413), \n at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110), \n at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58), \n at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38), \n at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62), \n at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), \n at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), \n at java.base/java.lang.reflect.Method.invoke(Method.java:566), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24), \n at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33), \n at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94), \n at com.sun.proxy.$Proxy2.processTestClass(Unknown Source), \n at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), \n at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), \n at java.base/java.lang.reflect.Method.invoke(Method.java:566), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24), \n at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182), \n at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164), \n at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414), \n at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64), \n at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48), \n at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), \n at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), \n at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56), \n at java.base/java.lang.Thread.run(Thread.java:834)]","output":""},{"name":"ctrl","status":"pass","message":"","output":""},{"name":"empty","status":"pass","message":"","output":""},{"name":"leading_and_trailing_spaces","status":"pass","message":"","output":""},{"name":"combine_conversions","status":"fail","message":"expected:<\"[_AbcĐ]CTRL\"> but was:<\"[9_AbcĐ\uD83D\uDE00\uDE00]CTRL\">org.junit.ComparisonFailure: expected:<\"[_AbcĐ]CTRL\"> but was:<\"[9_AbcĐ\uD83D\uDE00\uDE00]CTRL\">[\n at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method), \n at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62), \n at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45), \n at SqueakyCleanTest.combine_conversions(SqueakyCleanTest.java:64), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), \n at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), \n at java.base/java.lang.reflect.Method.invoke(Method.java:566), \n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59), \n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12), \n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56), \n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17), \n at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306), \n at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100), \n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366), \n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103), \n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63), \n at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331), \n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79), \n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329), \n at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66), \n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293), \n at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306), \n at org.junit.runners.ParentRunner.run(ParentRunner.java:413), \n at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110), \n at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58), \n at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38), \n at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62), \n at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), \n at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), \n at java.base/java.lang.reflect.Method.invoke(Method.java:566), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24), \n at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33), \n at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94), \n at com.sun.proxy.$Proxy2.processTestClass(Unknown Source), \n at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), \n at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), \n at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), \n at java.base/java.lang.reflect.Method.invoke(Method.java:566), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36), \n at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24), \n at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182), \n at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164), \n at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414), \n at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64), \n at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48), \n at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), \n at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), \n at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56), \n at java.base/java.lang.Thread.run(Thread.java:834)]","output":""},{"name":"kebab_to_camel_case","status":"pass","message":"","output":""},{"name":"single_letter","status":"pass","message":"","output":""}],"version":2}
```

Putting it into http://json.parser.online.fr/ shows the characters:
<img width="824" alt="Screenshot 2021-09-07 at 12 17 12" src="https://user-images.githubusercontent.com/286476/132336296-7e6611c3-4dcf-409f-a3d4-b50ed5a30ca3.png">

However, our systems just blow up trying to parse it.

I'm not sure what the solution is, but that's the problem here! :)

**Comment by iHiD** [comment]
This got fixed.
