### ISSUE TITLE
Segfaults are difficult to debug

### ISSUE THREAD

**Issue by hut8** [exercism/exercism#6316]
I'm on the x86-64 track right now. This platform is really great, so first, thanks so much for making it. I developed my solution locally, and tested it successfully. All the tests pass. I tried `make clean && make` just in case, and everything works fine. When I upload my solution, all I get is:

![image](https://user-images.githubusercontent.com/363720/161650073-7c2b92a6-feef-4178-8df4-ed1fbaec4df3.png)

☹️ It says that the core is dumped. If I get the core file, I could figure out what's wrong, but it doesn't look like it's available for download. Without that, I can't debug this because "it works on my machine." Any chance you could make broken artifacts available? Can I at least find out more details about exactly what platform it's compiled on?

Many thanks!

**Comment by hut8** [comment]
Perhaps this could also just be documentation that's added for x86-64. I'm open to suggestions. Having the core files available for download would be very awesome but also more difficult. Here's what I've done so far to help myself:

- Clone https://github.com/exercism/x86-64-assembly-test-runner
- On the *host*, run: `echo '/tmp/core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern`
- cd into `x86-64-assembly-test-runner`
- Add `cp -r * "$3"` into `run.sh` in order to get the source files and binaries out of the container and into the host's `output` directory
- Run `docker build -t test-runner .`
- Adapt docker-run.sh's command (just run the below)
```sh
docker run --init \
    --ulimit core=-1 \
    --mount type=bind,source=/tmp/,target=/tmp/ \
    -v $HOME/exercism/x86-64-assembly/two-fer:/mnt/exercism-iteration \
    -v $HOME/exercism/output:/output \
    test-runner two-fer /mnt/exercism-iteration/ /output/
```
The `--init` ensures proper signal handling, `--ulimit core=-1` make sure cores get created regardless of size, and the `--mount` is necessary in order to have the core get written and be accessible in the host. Other than that, it's the same as the regular command. 

I basically copied this straight from https://ddanilov.me/how-to-configure-core-dump-in-docker-container.

- The above command creates the core dump file in the hosts's /tmp.
- `cp /tmp/core.tests.* $HOME/exercism/output/`
- install gdb if necessary
- `cd $HOME/exercism/output`
- `gdb tests core.tests.*`

**Comment by hut8** [comment]
Another method (probably simpler) is adding `gdb` in the Dockerfile, changing the `Makefile` to directly invoke gdb on the `tests` binary, and adding ` --cap-add=SYS_PTRACE --security-opt seccomp=unconfined` when running `docker run` in addition to the above arguments in order to allow GDB to do certain things like disabling address space randomization. I'm still experimenting with the best way to debug in the container.

**Comment by hut8** [comment]
If I also add `musl-dbg` I can now see what's going on in ld-musl:

```
(gdb) run
         Starting program: /mnt/exercism-iteration/tests

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fc408c in do_relocs (dso=dso@entry=0x7ffff7ffd8a0 <app>, rel=0x555555554508, rel_size=216, stride=stride@entry=3) at ldso/dynlink.c:445
445     ldso/dynlink.c: No such file or directory.
```
I am somewhat surprised nobody else has run into this issue! It's strange to me that this doesn't even seem to be in my code, it's segfaulting in a dynamic link:

```
(gdb) bt
        #0  0x00007ffff7fc408c in do_relocs (dso=dso@entry=0x7ffff7ffd8a0 <app>, rel=0x555555554508, rel_size=216, stride=stride@entry=3) at ldso/dynlink.c:445
#1  0x00007ffff7fc4bde in reloc_all (p=p@entry=0x7ffff7ffd8a0 <app>) at ldso/dynlink.c:1316
#2  0x00007ffff7fc638a in __dls3 (sp=0x7fffffffecb0) at ldso/dynlink.c:1879
#3  0x00007ffff7fc5ba7 in __dls2b (sp=0x7fffffffecb0) at ldso/dynlink.c:1660
#4  0x00007ffff7fc5b4c in __dls2 (base=<optimized out>, sp=0x7fffffffecb0) at ldso/dynlink.c:1638
#5  0x00007ffff7fc3750 in _dlstart () from /lib/ld-musl-x86_64.so.1
#6  0x0000000000000001 in ?? ()
#7  0x00007fffffffeea3 in ?? ()
#8  0x0000000000000000 in ?? ()
```
